# Generated by Django 2.0.2 on 2018-02-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Neutrales', 'Neutrales'), ('Orden del Fénix', 'Orden del Fénix'), ('Marca Tenebrosa', 'Marca Tenebrosa'), ('Libros de Hechizos', 'Libros de Hechizos')], max_length=64, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spells.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('e', 'Efecto'), ('r', 'Rayo'), ('i', 'Invocación'), ('o', 'Invocación - Efecto'), ('ei', 'Efecto - Invocación'), ('eq', 'Equipable'), ('om', 'Onda Mágica'), ('ro', 'Rolistico')], default='e', max_length=2)),
                ('method', models.CharField(choices=[('V', 'Verbal'), ('N', 'No Verbal'), ('R', 'Rolistico')], default='V', max_length=1)),
                ('object', models.CharField(choices=[('V', 'Con Varita'), ('N', 'Sin Varita'), ('O', 'Objeto')], default='V', max_length=1)),
                ('battles', models.BooleanField(default=True)),
                ('range', models.ManyToManyField(to='spells.Range')),
            ],
        ),
    ]
