# Generated by Django 3.0.4 on 2020-03-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="spell", options={"ordering": ["name"]},),
        migrations.AlterField(
            model_name="range",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranges",
                to="spells.Group",
            ),
        ),
    ]
