# Generated by Django 3.0.4 on 2020-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0002_auto_20200325_2202"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                choices=[
                    ("Neutrales", "Neutrales"),
                    ("Orden del Fénix", "Orden del Fénix"),
                    ("Marca Tenebrosa", "Marca Tenebrosa"),
                    ("Libros de Hechizos", "Libros de Hechizos"),
                    ("Paladines", "Orden de la Mano de Plata"),
                    ("Oscuros", "Orden Oscura"),
                    ("Sacerdotes", "Orden de Avalón"),
                ],
                max_length=64,
                unique=True,
            ),
        ),
    ]
