# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0003_auto_20160902_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
