# Generated by Django 3.0.4 on 2020-03-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0003_auto_20200325_2310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spell",
            name="type",
            field=models.CharField(
                choices=[
                    ("e", "Efecto"),
                    ("r", "Rayo"),
                    ("i", "Invocación"),
                    ("o", "Invocación - Efecto"),
                    ("ei", "Efecto - Invocación"),
                    ("eq", "Equipable"),
                    ("om", "Onda Mágica"),
                    ("ro", "Rolistico"),
                    ("oe", "Onda Expansiva"),
                ],
                default="e",
                max_length=2,
            ),
        ),
    ]
