# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0004_auto_20160902_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='spell',
            old_name='type',
            new_name='group',
        ),
    ]
