# Generated by Django 3.0.4 on 2020-03-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0004_auto_20200325_2323"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spell", options={"ordering": ["-battles", "name"]},
        ),
    ]
