# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0005_auto_20160902_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='type',
            field=models.CharField(choices=[('e', 'Efecto'), ('r', 'Rayo'), ('i', 'Invocaci\xf3n')], default='e', max_length=1),
        ),
    ]
