# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0006_spell_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='slug',
            field=models.SlugField(editable=False, max_length=100),
        ),
    ]
