# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0007_auto_20160902_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=100),
        ),
    ]
