# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0008_auto_20160913_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(choices=[('N', 'Neutrales'), ('O', 'Orden del F\xe9nix'), ('M', 'Marca Tenebrosa'), ('LA', 'Libro del Aprendiz de Brujo'), ('LF', 'Libro de la Fortaleza'), ('LS', 'Libro de la Sangre'), ('LE', 'Libro del Equilibrio'), ('LD', 'Libro del Druida'), ('LO', 'Libro del Caos'), ('LAN', 'Libro de los Ancestros'), ('LAU', 'Libro de las Auras'), ('LH', 'Libro de Hermes Trimegisto'), ('LM', 'Libro de Merl\xedn')], max_length=4),
        ),
        migrations.RemoveField(
            model_name='spell',
            name='group',
        ),
        migrations.AddField(
            model_name='spell',
            name='group',
            field=models.ManyToManyField(to='spells.Group'),
        ),
    ]
