# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0011_auto_20160916_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='method',
            field=models.CharField(choices=[('V', 'Verbal'), ('N', 'No Verbal')], default='V', max_length=1),
        ),
        migrations.AddField(
            model_name='spell',
            name='object',
            field=models.CharField(choices=[('V', 'Con Varita'), ('N', 'Sin Varita'), ('O', 'Anillo, Colgante, etc')], default='V', max_length=1),
        ),
    ]
