# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0015_auto_20160920_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='type',
            field=models.CharField(choices=[('e', 'Efecto'), ('r', 'Rayo'), ('i', 'Invocaci\xf3n'), ('o', 'Invocaci\xf3n - Efecto'), ('ei', 'Efecto - Invocaci\xf3n'), ('eq', 'Equipable'), ('om', 'Onda M\xe1gica')], default='e', max_length=2),
        ),
    ]
