# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0016_auto_20160920_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(choices=[('Neutrales', 'Neutrales'), ('Orden del F\xe9nix', 'Orden del F\xe9nix'), ('Marca Tenebrosa', 'Marca Tenebrosa'), ('Libro del Aprendiz de Brujo', 'Aprendiz de Brujo'), ('Libro de la Fortaleza', 'Fortaleza'), ('Libro de la Sangre', 'Sangre'), ('Libro del Equilibrio', 'Equilibrio'), ('Libro del Druida', 'Druida'), ('Libro del Caos', 'Caos'), ('Libro de los Ancestros', 'Ancestros'), ('Libro de las Auras', 'Auras'), ('Libro de Hermes Trimegisto', 'Hermes Trimegisto'), ('Libro de Merl\xedn', 'Merl\xedn')], max_length=64, unique=True),
        ),
    ]
