# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0017_auto_20160921_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='object',
            field=models.CharField(choices=[('V', 'Con Varita'), ('N', 'Sin Varita'), ('O', 'Objeto')], default='V', max_length=1),
        ),
    ]
