# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0018_auto_20160921_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spells.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='spell',
            name='group',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='range',
        ),
    ]
