# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0019_auto_20160922_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spells.Range'),
        ),
    ]
