# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0020_spell_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='range',
        ),
        migrations.AddField(
            model_name='spell',
            name='range',
            field=models.ManyToManyField(to='spells.Range'),
        ),
    ]
