# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0022_range_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
