# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0023_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(choices=[('Neutrales', 'Neutrales'), ('Orden del F\xe9nix', 'Orden del F\xe9nix'), ('Marca Tenebrosa', 'Marca Tenebrosa'), ('Libros de Hechizos', 'Libros de Hechizos')], max_length=64, unique=True),
        ),
    ]
