# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0024_auto_20160924_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='battles',
            field=models.BooleanField(default=True),
        ),
    ]
