# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0025_spell_battles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='method',
            field=models.CharField(choices=[('V', 'Verbal'), ('N', 'No Verbal'), ('R', 'Rolistico')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='spell',
            name='type',
            field=models.CharField(choices=[('e', 'Efecto'), ('r', 'Rayo'), ('i', 'Invocaci\xf3n'), ('o', 'Invocaci\xf3n - Efecto'), ('ei', 'Efecto - Invocaci\xf3n'), ('eq', 'Equipable'), ('om', 'Onda M\xe1gica'), ('r', 'Rolistico')], default='e', max_length=2),
        ),
    ]
